# 1. IMPORTING NUMPY

In [2]:
import numpy as np

# 2. NUMPY ARRAYS

In [4]:
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a= np.arange(10)
a                           # ARRAY

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b=np.arange(20)
b.ndim                       # DIMENSION

1

In [26]:
c=np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [27]:
c.ndim

2

In [28]:
d=([[1,2,3],[4,5,6],[7,8,9]])
d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [32]:
e= np.arange(30).reshape(5,6)
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
e.shape

(5, 6)

In [40]:
e.ndim

2

In [41]:
e.size

30

In [42]:
type (e)

numpy.ndarray

In [46]:
f=np.zeros([2,4])
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
g=np.arange(15).reshape(5,3)
g

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# 3. NUMPY COMMANDS

* VSTACK
* HSTACK
* RANDOM
* FLOOR
* CEIL
* HSPLIT
* VSPLIT
* COPYING ARRAY

H STACK AND V STACK

In [56]:
h=np.arange(15).reshape(3,5)
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
i=np.arange(25).reshape(5,5)
i

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
np.vstack((h,i))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
j=np.arange(18).reshape(3,6)
j

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [74]:
np.hstack((h,j))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9,  6,  7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14, 12, 13, 14, 15, 16, 17]])

RANDOM

In [86]:
np.random.random()

0.3942811736766275

In [87]:
np.random.random((2,3))

array([[0.43746065, 0.17793633, 0.79564204],
       [0.36022255, 0.81929364, 0.81375674]])

FLOOR

In [88]:
np.floor(10.4)

10.0

In [89]:
np.floor(25.5)

25.0

CEIL

In [90]:
np.ceil(10.4)

11.0

In [91]:
np.ceil(25.5)

26.0

H SPLIT

In [94]:
k=np.arange(30).reshape(5,6)
k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [105]:
l=np.hsplit(k,3)
l

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

V SPLIT

In [107]:
m=np.arange(30).reshape(6,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [108]:
n=np.vsplit(m,3)
n

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

RANDOM , FLOOR, MULTIPLCATION

In [116]:
p=100*np.floor(np.random.random((2,4)))
p

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

COPYING ARRAYS

In [124]:
r=np.arange(4)
r

array([0, 1, 2, 3])

In [126]:
s=r
s

array([0, 1, 2, 3])

In [129]:
r[3]=200

In [130]:
s

array([  0,   1,   2, 200])

In [131]:
r

array([  0,   1,   2, 200])